language: java

jdk:
    - openjdk14
    
addons:
    sonarcloud:
        organization: "gabrielequatrana"
        token: "19ffc48e2289ebec400b39caff8340d3cdb15749"

script:
    - mvn compile
    - mvn test
    - mvn package
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gabrielequatrana_test-jcs-1.3