language: java

jdk:
    - openjdk14
    
dist:
    - xenial
    
os:
    - linux
    
git:
  depth: false
    
addons:
  sonarcloud:
    organization: "gabrielequatrana"
    token: "923e5e837e9fe5d4174e770f5dfca1e808404f7b" 
  
notifications:
    email:
        on_success: never
        on_failure: never

script:
    #- mvn clean verify
    #- sonar-scanner
    #- mvn clean
    #- mvn test
    - mvn clean verify sonar:sonar
