language: java

jdk:
    - openjdk14
     
os:
    - linux
    
dist:
    - xenial
    
git:
  depth: false
    
addons:
  sonarcloud:
    organization: "gabrielequatrana"
    token: "923e5e837e9fe5d4174e770f5dfca1e808404f7b" 

script:
    - mvn clean -P coverageProfile org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report verify sonar:sonar
    - ls -l target/jacoco-gen/jcs-coverage/