language: java

jdk:
    - openjdk14
    
addons:
    sonarcloud:
        organization: "gabrielequatrana"
        token: "19ffc48e2289ebec400b39caff8340d3cdb15749"
        
notifications:
    email:
        on_success: never
        on_failure: never

script:
    - mvn compile
    - mvn test
    - mvn package
    - mvn clean
    
