language: java

jdk:
    - openjdk14
    
dist:
    - xenial
    
os:
    - linux
    
addons:
  sonarcloud:
    organization: "gabrielequatrana"
    token: "77d4ac518583d71716915406b67f1bdbac9e5dbb" 
  
notifications:
    email:
        on_success: never
        on_failure: never

script:
    - mvn clean verify
    - sonar-scanner
    
